### ISSUE TITLE
Fix several inconsistent bugs

### ISSUE THREAD

**Issue by GhostofGoes** [GhostofGoes/Python-Game-Reloaded#2]
These are occurring seemingly at random on start

```
PS Python-Game-Reloaded>python .\Game.py
Traceback (most recent call last):
  File ".\Game.py", line 112, in <module>
    game.run()
  File ".\Game.py", line 41, in run
    gameNotOver = self.runGame()
  File ".\Game.py", line 56, in runGame
    self.playerObj = Player.Player()
  File "C:\Users\goesc\Documents\Projects\Python-Game-Reloaded\Player.py", line 92, in __init__
    self.range, 1)
```

```
PS Python-Game-Reloaded>python .\Game.py
Traceback (most recent call last):
  File ".\Game.py", line 112, in <module>
    game.run()
  File ".\Game.py", line 41, in run
    gameNotOver = self.runGame()
  File ".\Game.py", line 84, in runGame
    spawnner.drawSpawnner()
  File "C:\Users\goesc\Documents\Projects\Python-Game-Reloaded\Spawnner.py", line 38, in drawSpawnner
    self.size / 2)
TypeError: integer argument expected, got float
```

**Comment by GhostofGoes** [comment]
These are being caused by changes to division operator in Python 3
